good_loot = [
    ("+100 TO LIFE", "SOCKETED (4)"),
    ("+24% FASTER HIT RECOVERY", "SOCKETED (4)"),
    ("+3 TO JAVELIN AND SPEAR SKILLS", "+20% INCREASED ATTACK SPEED"),
    ("+3 TO MARTIAL ARTS", "+20% INCREASED ATTACK SPEED"),
    ("+3 TO MARTIAL ARTS", "+3 TO LIGHTNING SENTRY"),
    ("+3 TO VENOM", "+2 TO ASSASSIN SKILLS"),
    ("COLD RESIST +40%", "+40% FASTER RUN/WALK"),
    ("LIGHTNING RESIST +40%", "+40% FASTER RUN/WALK"),
    ("RESIST +30%", "+100 TO LIFE"),
]
