good_loot = [
    "SMALL CHARM",
    "GRAND CHARM",
    "RING",
    "JEWEL",
    "FLAWLESS",
    "GOLD",
    "ZOD RUNE",
    "CHAM RUNE",
    "JAH RUNE",
    "BER RUNE",
    "SUR RUNE",
    "LO RUNE",
    "OHM RUNE",
    "VEX RUNE",
    "GUL RUNE",
    "IST RUNE",
]